import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle, Clock, MapPin, PhoneCall, Radio, RefreshCw, ShieldAlert } from 'lucide-react';
import { getHotspots, RiskPoint } from '../../lib/api';

interface ActiveWarningsViewProps { onNavigateDistrict: (districtId: string) => void; }

export function ActiveWarningsView({ onNavigateDistrict }: ActiveWarningsViewProps) {
  const [points, setPoints] = useState<RiskPoint[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState<'all'|'HIGH'|'MEDIUM'>('all');

  const load = async () => {
    try { setError(''); const data = await getHotspots(20); setPoints(data.hotspots || []); }
    catch (e) { console.error(e); setError('Unable to load the live risk watchlist.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); const t=window.setInterval(load,5*60*1000); return()=>clearInterval(t); }, []);

  const alerts = useMemo(() => points.filter(p => p.risk === 'HIGH' || p.risk === 'MEDIUM').filter(p => filter === 'all' || p.risk === filter), [points,filter]);
  const high = points.filter(p=>p.risk==='HIGH').length;
  const medium = points.filter(p=>p.risk==='MEDIUM').length;

  return <div className="w-full min-h-screen bg-[#f8fafc] dark:bg-[#071118] text-slate-900 dark:text-slate-100 py-8 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
    <div className="pb-6 border-b border-slate-200 dark:border-slate-800 flex flex-col lg:flex-row lg:items-center justify-between gap-4">
      <div><div className="flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full bg-red-500 animate-pulse"/><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">Live Risk Watchlist</h1><span className="text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300">LIVE RISK INDEX</span></div><p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-1">Current highest-risk monitored locations from live environmental inputs. These are prototype risk estimates, not official government warnings.</p></div>
      <div className="flex items-center gap-2"><div className="px-3 py-2 rounded-lg border border-red-200 dark:border-red-900/60 bg-red-50 dark:bg-red-950/30"><b className="text-red-700 dark:text-red-300 text-sm">{high}</b><span className="ml-1 text-[10px] uppercase font-bold text-red-600 dark:text-red-400">High</span></div><div className="px-3 py-2 rounded-lg border border-amber-200 dark:border-amber-900/60 bg-amber-50 dark:bg-amber-950/30"><b className="text-amber-700 dark:text-amber-300 text-sm">{medium}</b><span className="ml-1 text-[10px] uppercase font-bold text-amber-600 dark:text-amber-400">Medium</span></div><button type="button" onClick={load} className="p-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-800" title="Refresh"><RefreshCw className="w-4 h-4"/></button></div>
    </div>

    <div className="my-6 flex flex-wrap gap-2"><button onClick={()=>setFilter('all')} className={`px-3 py-1.5 rounded-md text-xs font-bold ${filter==='all'?'bg-[#1b4d3e] text-white':'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700'}`}>All ({high+medium})</button><button onClick={()=>setFilter('HIGH')} className={`px-3 py-1.5 rounded-md text-xs font-bold ${filter==='HIGH'?'bg-red-600 text-white':'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-red-600 dark:text-red-400'}`}>High ({high})</button><button onClick={()=>setFilter('MEDIUM')} className={`px-3 py-1.5 rounded-md text-xs font-bold ${filter==='MEDIUM'?'bg-amber-600 text-white':'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-amber-600 dark:text-amber-400'}`}>Medium ({medium})</button></div>

    {error && <div className="mb-4 p-4 rounded-xl border border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-200 text-sm">{error} <button type="button" onClick={load} className="ml-2 underline font-bold">Retry</button></div>}
    {loading ? <div className="py-16 text-center text-sm text-slate-500"><RefreshCw className="w-6 h-6 mx-auto mb-3 animate-spin"/>Loading live risk watchlist…</div> : error ? <div className="p-10 text-center bg-white dark:bg-[#0e1922] rounded-xl border border-slate-200 dark:border-slate-800"><Radio className="w-9 h-9 text-amber-500 mx-auto mb-3"/><div className="font-bold">Live risk data unavailable</div><div className="text-xs text-slate-500 mt-1">No risk ranking is shown until the environmental feed reconnects.</div></div> : alerts.length===0 ? <div className="p-10 text-center bg-white dark:bg-[#0e1922] rounded-xl border border-slate-200 dark:border-slate-800"><CheckCircle className="w-9 h-9 text-emerald-500 mx-auto mb-3"/><div className="font-bold">No current high/medium locations</div><div className="text-xs text-slate-500 mt-1">Risk estimates update automatically every five minutes.</div></div> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{alerts.map((p,i)=>{const highRisk=p.risk==='HIGH'; return <button type="button" key={p.id} onClick={()=>onNavigateDistrict(p.id)} className={`text-left p-5 rounded-xl border transition hover:-translate-y-0.5 hover:shadow-md ${highRisk?'border-red-200 dark:border-red-900/70 bg-red-50/50 dark:bg-red-950/20':'border-amber-200 dark:border-amber-900/70 bg-amber-50/50 dark:bg-amber-950/20'}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className={`px-2 py-1 rounded text-[10px] font-extrabold text-white ${highRisk?'bg-red-600':'bg-amber-600'}`}>{p.risk}</span><span className="text-[10px] font-mono text-slate-500">RANK #{i+1}</span></div><AlertTriangle className={`w-5 h-5 ${highRisk?'text-red-500':'text-amber-500'}`}/></div><h3 className="mt-3 text-lg font-bold">{p.name}</h3><div className="flex items-center gap-1 text-xs text-slate-600 dark:text-slate-400"><MapPin className="w-3.5 h-3.5"/>{p.state}</div><div className="grid grid-cols-3 gap-2 mt-4"><div className="p-2 rounded bg-white/70 dark:bg-slate-900/60"><div className="text-[9px] uppercase text-slate-400">Risk score</div><b className="text-sm">{p.risk_score!=null?(p.risk_score*100).toFixed(1)+'%':'—'}</b></div><div className="p-2 rounded bg-white/70 dark:bg-slate-900/60"><div className="text-[9px] uppercase text-slate-400">Rain / 24h</div><b className="text-sm">{p.rainfall_24h_mm!=null?p.rainfall_24h_mm.toFixed(1)+' mm':'—'}</b></div><div className="p-2 rounded bg-white/70 dark:bg-slate-900/60"><div className="text-[9px] uppercase text-slate-400">Soil</div><b className="text-sm">{p.soil_moisture_vol_frac!=null?p.soil_moisture_vol_frac.toFixed(3):'—'}</b></div></div><div className="mt-3 flex items-center gap-2 text-[10px] text-slate-500 dark:text-slate-400"><Radio className="w-3.5 h-3.5 text-emerald-500"/> {p.status} · live environmental input</div></button>})}</div>}

    <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4"><div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0e1922]"><ShieldAlert className="w-5 h-5 text-emerald-500 mb-2"/><b className="text-sm">What this means</b><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Watchlist ranking is based on the current risk score, not an official warning level.</p></div><div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0e1922]"><Clock className="w-5 h-5 text-blue-500 mb-2"/><b className="text-sm">Refresh cadence</b><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">The map and watchlist refresh approximately every five minutes.</p></div><div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0e1922]"><PhoneCall className="w-5 h-5 text-red-500 mb-2"/><b className="text-sm">Emergency</b><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">For emergencies, use your local emergency/disaster-management services.</p></div></div>
  </div>;
}
